service: step-function-service
frameworkVersion: ">=1.11.0 <2.0.0"
provider:
  name: aws
  apiKeys:
    - ${self:service}-${opt:stage}-internal
  runtime: nodejs12.x
  versionFunctions: false
  cfLogs: true
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: production
    STAGE: ${opt:stage}
    LOG_LEVEL: ${self:custom.logLevel.${opt:stage}, self:custom.logLevel.default}

plugins:
  - serverless-offline

custom:
  logLevel:
    production: WARN
    default: DEBUG

package:
  exclude:
    - src/**/*.test.js
    - src/**/*.snap
    - '.*'
    - '*.sh'
    - package.json
    - yarn.lock
    - README.md

functions:
  firstState:
    handler: src/states/first-state.handler
